{{- if and (not .Values.auth.existingSecret) (or .Values.auth.adminPasswordHash .Values.auth.apiToken) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mikrotik-wireguard.fullname" . }}-auth
  labels:
    {{- include "mikrotik-wireguard.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.auth.adminPasswordHash }}
  admin-hash: {{ .Values.auth.adminPasswordHash | quote }}
  {{- end }}
  {{- if .Values.auth.apiToken }}
  api-token: {{ .Values.auth.apiToken | quote }}
  {{- end }}
{{- end }}
